### ISSUE TITLE
Rendering the tab after applying a filter in modal

### ISSUE THREAD

**Issue by isalcedo** [dpodium/yii2-filemanager#12]
Can someone please confirm this issue?

When I try to apply a filter in the Library tab when I'm looking it in modal mode the Ajax call return a 404 error. I do know where the problem is it, but I need confirmation before make a pull request with the fix inside the filemanajer.js file.

**Comment by dpodium-github** [comment]
Hi, we have looked into the issue. Unfortunately, we were unable to reproduce the same error. Can you provide to us your domain which you hit to received this 404 error? Thanks.

**Comment by isalcedo** [comment]
I'll make a pull request. Hopefully the change made inside filemanaher.js is kinda neutral so can't break anything that work and solve my case. Maybe is because I running this component inside a Yii2-advanced project with custom route (public_html and public_html/admin)

Please, my English sucks some times.

**Comment by isalcedo** [comment]
Fixed in #13
