### ISSUE TITLE
Can not get zip archive files

### ISSUE THREAD

**Issue by bahrammzm** [dpodium/yii2-filemanager#20]
when i trying to upload zip archive file , it returns below error . Note that i specified acceptedFilesType => "*" in module configurations . it works perfectly with another file types even another archive formats such as .rar , 7z. 

![capture](https://user-images.githubusercontent.com/15061349/35671816-cc07ce98-0751-11e8-8d45-542a06841f8e.JPG)

**Comment by priyankadpodium** [comment]
Hi, We have tested with PHP version 5.6, 7, 7.1. Upload feature is working on mentioned version. You may test on one of those versions if you are using some other version. If you still face issues, feel free to drop us another message with error log. Thanks.

**Comment by bahrammzm** [comment]
I have tested with version 5.6.31 , 7.0.23 . still issue remaining . below image shows .rar file example . but about .zip files i facing same upper problem that shows file attributes are null .
![rar](https://user-images.githubusercontent.com/15061349/35722788-ebdb8dde-080c-11e8-9bda-7b6898e40a8e.JPG)

**Comment by priyankadpodium** [comment]
Hi, Can you attach the file you are trying to upload as well? As per your log, there is no error while uploading the file. We will require the file to look into the issue. Thanks.
